# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(
                choices=[('dr_deepak_chandra_srivastava', 'Dr. Deepak Chandra Srivastava')],
                default='dr_deepak_chandra_srivastava',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.CharField(
                choices=[('osborn_bargadwa', 'Osborn Clinic - Bargadwa, Gorakhpur')],
                default='osborn_bargadwa',
                max_length=50,
            ),
        ),
    ]
