# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment_doctor_clinic_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(
                choices=[
                    ('consultation', 'Consultation'),
                    ('dialysis_cat', 'Dialysis Catheter Placement'),
                    ('central_line', 'Central Line Insertion'),
                    ('renal_biopsy', 'Renal Biopsy'),
                    ('lumbar_punct', 'Lumbar Puncture'),
                    ('bone_marrow', 'Bone Marrow Biopsy'),
                ],
                default='consultation',
                max_length=20,
            ),
        ),
    ]
