# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_appointment_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('selected_tests', models.TextField()),
                ('collection_mode', models.CharField(choices=[('home_collection', 'Home Collection'), ('lab_visit', 'Lab Visit')], default='home_collection', max_length=20)),
                ('branch', models.CharField(choices=[('osborn_bargadwa', 'Osborn Pathology - Bargadwa, Gorakhpur')], default='osborn_bargadwa', max_length=50)),
                ('collection_address', models.TextField(blank=True)),
                ('preferred_date', models.DateField()),
                ('referral_doctor', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('collected', 'Sample Collected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('delivery_mode', models.CharField(choices=[('home_delivery', 'Home Delivery'), ('store_pickup', 'Store Pickup')], default='home_delivery', max_length=20)),
                ('branch', models.CharField(choices=[('osborn_bargadwa', 'Osborn Pharmacy - Bargadwa, Gorakhpur')], default='osborn_bargadwa', max_length=50)),
                ('delivery_address', models.TextField(blank=True)),
                ('prescription_upload', models.FileField(blank=True, upload_to='prescriptions/')),
                ('medicine_list', models.TextField(blank=True)),
                ('preferred_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
