# Generated by Codex on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_CLINIC = {
    "name": "Osborn Clinic - Bargadwa",
    "slug": "osborn-bargadwa",
    "address": (
        "Osborn Clinic, Nehru Complex, Shop No. 50, Near SBI Bank, "
        "Bargadwa Nakaha Road, Vikas Nagar, Gorakhpur 273007"
    ),
    "phone": "+91 9760901297",
    "email": "drdeepakchandrasrivastava@gmail.com",
    "operating_hours": "8:00 AM - 10:00 AM and 3:00 PM - 8:00 PM. Thursday closed.",
    "services_offered": "Doctor Consultation, Pharmacy, Pathology, Home Collection",
    "offers_consultation": True,
    "offers_pharmacy": True,
    "offers_pathology": True,
    "google_maps_url": "https://maps.app.goo.gl/rtrWqpUd5y4uEi2h8",
    "map_embed_url": (
        "https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d1588.126372110541"
        "!2d83.35646060911094!3d26.80472274187001!2m3!1f0!2f0!3f0!3m2!1i1024"
        "!2i768!4f13.1!3m2!1m1!2zMjbCsDQ4JzIwLjAiTiA4M8KwMjEnMjMuMSJF!5e0"
        "!3m2!1sen!2sin!4v1765049098606!5m2!1sen!2sin"
    ),
}


def seed_default_clinic(apps, schema_editor):
    Clinic = apps.get_model("main", "Clinic")
    Appointment = apps.get_model("main", "Appointment")
    PharmacyOrder = apps.get_model("main", "PharmacyOrder")
    PathologyBooking = apps.get_model("main", "PathologyBooking")

    clinic, _ = Clinic.objects.get_or_create(
        slug=DEFAULT_CLINIC["slug"],
        defaults=DEFAULT_CLINIC,
    )

    Appointment.objects.filter(clinic_ref__isnull=True).update(clinic_ref_id=clinic.pk)
    PharmacyOrder.objects.filter(branch_ref__isnull=True).update(branch_ref_id=clinic.pk)
    PathologyBooking.objects.filter(branch_ref__isnull=True).update(branch_ref_id=clinic.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_pharmacyorder_pathologybooking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("operating_hours", models.CharField(blank=True, max_length=160)),
                ("services_offered", models.TextField(blank=True)),
                ("offers_consultation", models.BooleanField(default=True)),
                ("offers_pharmacy", models.BooleanField(default=False)),
                ("offers_pathology", models.BooleanField(default=False)),
                ("map_embed_url", models.URLField(blank=True, max_length=1000)),
                ("google_maps_url", models.URLField(blank=True, max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="clinic_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="main.clinic",
            ),
        ),
        migrations.AddField(
            model_name="pharmacyorder",
            name="branch_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="main.clinic",
            ),
        ),
        migrations.AddField(
            model_name="pathologybooking",
            name="branch_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="main.clinic",
            ),
        ),
        migrations.RunPython(seed_default_clinic, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="appointment",
            name="clinic",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="pharmacyorder",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="pathologybooking",
            name="branch",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="clinic_ref",
            new_name="clinic",
        ),
        migrations.RenameField(
            model_name="pharmacyorder",
            old_name="branch_ref",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="pathologybooking",
            old_name="branch_ref",
            new_name="branch",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="main.clinic",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("consultation", "Consultation"),
                    ("dialysis_cat", "Dialysis Catheter Placement"),
                    ("central_line", "Central Line Insertion"),
                    ("renal_biopsy", "Renal Biopsy"),
                    ("lumbar_punct", "Lumbar Puncture"),
                    ("bone_marrow", "Bone Marrow Biopsy"),
                ],
                default="consultation",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="pharmacyorder",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pharmacy_orders",
                to="main.clinic",
            ),
        ),
        migrations.AlterField(
            model_name="pathologybooking",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pathology_bookings",
                to="main.clinic",
            ),
        ),
    ]
