# Generated by Codex on 2026-05-17

from django.db import migrations, models


UPDATED_SERVICES = (
    "Internal Medicine, Kidney Disease & Nephrology Care, Hypertension Treatment, "
    "Diabetes Management, Fever & Infection Treatment, Thyroid & Lifestyle Disorders, "
    "Chronic Disease Care, Preventive Health Checkups, Pharmacy, Pathology, Home Collection"
)


def update_clinic_services(apps, schema_editor):
    Clinic = apps.get_model("main", "Clinic")
    Clinic.objects.filter(slug="osborn-bargadwa").update(services_offered=UPDATED_SERVICES)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_multi_location_clinic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("consultation", "General Physician Consultation"),
                    ("internal_medicine", "Internal Medicine Consultation"),
                    ("kidney_care", "Kidney Disease & Nephrology Care"),
                    ("hypertension", "High Blood Pressure Treatment"),
                    ("diabetes", "Diabetes Management"),
                    ("fever_infection", "Fever & Infection Treatment"),
                    ("thyroid_lifestyle", "Thyroid & Lifestyle Disorders"),
                    ("preventive_checkup", "Preventive Health Checkup"),
                    ("dialysis_counselling", "Dialysis Counselling & Kidney Protection"),
                ],
                default="consultation",
                max_length=32,
            ),
        ),
        migrations.RunPython(update_clinic_services, migrations.RunPython.noop),
    ]
