# Generated by Codex on 2026-05-18

from django.db import migrations, models


NEW_BRANCHES = [
    {
        "name": "Osborn Clinic - Mehdawal",
        "slug": "osborn-mehdawal",
        "address": "Beside Indian Oil Petrol Pump, Tehsil Road, Mehdawal, Sant Kabir Nagar",
        "phone": "+91 6387469689",
        "alternate_phone": "+91 9760901297",
        "operating_hours": "Every Thursday, 10:00 AM - 5:00 PM",
        "services_offered": (
            "Internal Medicine, Kidney Disease & Nephrology Care, Hypertension Treatment, "
            "Diabetes Management, Creatinine & Kidney Function Evaluation, Urine Protein Evaluation, "
            "Dialysis Counselling"
        ),
        "offers_consultation": True,
        "offers_pharmacy": False,
        "offers_pathology": False,
        "is_active": True,
        "sort_order": 10,
    },
    {
        "name": "Osborn Clinic - Tamkuhi Road",
        "slug": "osborn-tamkuhi-road",
        "address": "Near Bajaj Agency, Main Road, Tamkuhi Road",
        "phone": "+91 6387469689",
        "alternate_phone": "+91 6389207188",
        "operating_hours": "Every Saturday, 10:00 AM - 5:00 PM",
        "services_offered": (
            "Internal Medicine, Kidney Disease & Nephrology Care, Hypertension Treatment, "
            "Diabetes Management, CKD Screening, Creatinine & Kidney Function Evaluation, "
            "Preventive Health Checkups"
        ),
        "offers_consultation": True,
        "offers_pharmacy": False,
        "offers_pathology": False,
        "is_active": True,
        "sort_order": 20,
    },
]


def add_new_branches(apps, schema_editor):
    Clinic = apps.get_model("main", "Clinic")
    for branch in NEW_BRANCHES:
        Clinic.objects.update_or_create(
            slug=branch["slug"],
            defaults=branch,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_update_healthcare_service_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="alternate_phone",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(add_new_branches, migrations.RunPython.noop),
    ]
