# Generated by Django 4.2.30 on 2026-09-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_saathi_chat_log_error_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='external_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
