name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main   # or 'master' or your chosen branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update code on PythonAnywhere
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/${{ secrets.PA_DOMAIN_NAME }}/reload/" \
        -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}"
